export default {
    mainWindow: null,
    launcherWindow: null,
    overviewWindow: null,
    settingsWindow: null,
    selectedSerial: null,
    selectedAlias: null,
    selectedModel: null,
    currentVideoRatio: 1,
    currentSidebarWidth: 0,
    notificationCache: [],
    notificationWatcher: null,
    isScrcpyStarted: false,
    scrcpyProc: null,
    videoSocket: null,
    audioSocket: null,
    controlSocket: null,
    streamHistory: [],
    isScrcpyDownloading: false,
    isAdbReady: false,
    debugStatsEnabled: false,
    debugConnTimeEnabled: false,
};
